# 应用端口/服务名配置
server:
  host: 192.168.11.249
  port: 8003
  servlet:
    context-path: /ocr
# mysql数据源配置
spring:
  application:
    name: ocr
  servlet:
    multipart:
      max-file-size: -1 # 限制文件上传的大小
      max-request-size: -1
  mvc:
    static-path-pattern: /**  #表示所有的访问都经过静态资源路径
    async:
      request-timeout: 100000 #设置超时时间为100s，原因是某些ofd文件过大
  resources:
    static-locations: classpath:/static/,file:/usr/local/ocr/media/  #配置静态资源路径，最后面是上传文件保存路径
app-file-path: /usr/local/ocr/
tessdata-path: /usr/local/ocr/tessdata

